name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ip-get-super-super:
    runs-on: ubuntu-latest
    steps:
      - run: ip a
      - run: ls /
      - run: cd ..